root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
args_bin = []
cmd = "go build -o build/user/main cmd/user/main.go"
bin = "build/user/main"
delay = 1000
follow_symlink = false
full_bin = ""
include_dir = ["internal/user", "cmd/user", "api/user", "configs/user"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["internal/*", "assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
exclude_unchanged = false
exclude_file = []
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
