services:
  ####################### Application #######################
  user-prod:
    build:
      context: ../../..
      dockerfile: deployments/user/production/Dockerfile
      target: production
    container_name: go-monorepo-microsvc-clean-arch_user-production
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${GRPC_PORT}:${GRPC_PORT}"
    volumes:
      - ./../../../:/app
    networks:
      - go-monorepo-microsvc-clean-arch_network
    depends_on:
      - mysqldb
      - redis
    #      - rabbitmq
